"""Regenerate the approved LibreOffice renderer baseline.

The renderer baseline is the *second* level of the dual-reference system:

- ``references/`` holds the original Excel screenshots (the human/design
  reference). They are never regenerated by this project.
- ``tests/visual/baselines/libreoffice/`` holds PNGs produced by this exact
  render pipeline from the approved fixture workbook, plus a ``manifest.json``
  recording LibreOffice/poppler versions, platform, DPI, dimensions, SHA-256
  hashes, generation date and the command used.

Regeneration is always explicit: it requires ``--confirm`` and never happens
as a side effect of running the comparison or the test suite, so an approved
baseline can never be silently overwritten by a regression.

Usage::

    python scripts/update_visual_baseline.py --confirm
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tempfile

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))

from compare_excel_visual import (  # noqa: E402
    BASELINE_DIR,
    missing_python_deps,
    missing_render_tools,
    validate_workbook_against_spec,
    write_baseline,
)
from sample_workbook import export_sample_workbook  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--confirm",
        action="store_true",
        help="Required. Confirms that the current render is approved as the new baseline.",
    )
    parser.add_argument("--workbook", type=Path, default=None, help="Approved workbook. Default: the fixture sample workbook.")
    parser.add_argument("--baseline-dir", type=Path, default=BASELINE_DIR)
    args = parser.parse_args(argv)

    if not args.confirm:
        print(
            "Refusing to overwrite the approved baseline without --confirm.\n"
            "Review the design-mode diff first (python scripts/compare_excel_visual.py --mode design), "
            "then re-run with --confirm."
        )
        return 2

    tool_gaps = missing_render_tools()
    if tool_gaps:
        print(f"ERROR: missing rendering tools {', '.join(tool_gaps)}. Install LibreOffice and poppler-utils.")
        return 2
    dep_gaps = missing_python_deps()
    if dep_gaps:
        print(f"ERROR: missing optional Python dependencies {', '.join(dep_gaps)}. Install with `pip install -e .[visual]`.")
        return 2

    with tempfile.TemporaryDirectory() as tmp:
        workbook_path = args.workbook or export_sample_workbook(Path(tmp) / "sample_workbook.xlsx")
        validate_workbook_against_spec(workbook_path)
        manifest = write_baseline(workbook_path, args.baseline_dir, Path(tmp))

    print(f"Baseline written to {args.baseline_dir}")
    print(f"  LibreOffice: {manifest['libreoffice_version']}")
    print(f"  poppler:     {manifest['pdftoppm_version']}")
    print(f"  platform:    {manifest['platform']}")
    print(f"  dpi:         {manifest['dpi']}")
    for sheet_name, entry in manifest["sheets"].items():
        print(f"  {sheet_name:<24} {entry['file']:<26} {tuple(entry['dimensions'])!s:<12} sha256={entry['sha256'][:16]}…")
    print("Commit the PNGs and manifest.json only after reviewing the design-mode diff.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
